/** @file superloop.h
 *
 * @brief This module contains the firmware superloop, code in here should be
 * added to the main function generated by the CubeMX tools. By convention we
 * want this to be the only module accessed from the CubeMX generated main
 * function.
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2025 DalMAST.  All rights reserved.
 */

 #ifndef SUPERLOOP_H
 #define SUPERLOOP_H
 
 #include <stdint.h>
 
 void superloop_init(void);
 void superloop_run(void);
 
 #endif /* SUPERLOOP_H */
 
 /*** end of file ***/