/** @file superloop.c
 *
 * @brief This module contains the firmware superloop, code in here should be
 * added to the main function generated by the CubeMX tools. By convention we
 * want this to be the only module accessed from the CubeMX generated main
 * function.
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2025 DalMAST. All rights reserved.
 */

 #include "superloop.h"

 // CubeMx-generated header files:
 #include "stm32h5xx_hal.h"
 // User-generated header files:
 #include "blink.h"
 
 /*!
  * @brief This function should be called before the superloop.
  */
 void
 superloop_init (void)
 {
     blink_init();
 }
 
 /*!
  * @brief This function should be called within the superloop.
  */
 void
 superloop_run (void)
 {
     blink_superloop();
 }